# Generated by Django 3.0.5 on 2020-08-04 14:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='registration',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
