# Generated by Django 3.0.5 on 2020-08-04 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order_date', models.DateField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='products.Product')),
            ],
        ),
    ]
